version: "3"
services:
    shinobi:
        image: registry.gitlab.com/shinobi-systems/shinobi:dev
        container_name: Shinobi
        environment:
           - PLUGIN_KEYS={}
           - SSL_ENABLED=false
        volumes:
           - /home/joss/data/shinobi/config:/config
           - /home/joss/data/shinobi/customAutoLoad:/home/Shinobi/libs/customAutoLoad
           - /home/joss/data/shinobi/database:/var/lib/mysql
           - /home/joss/data/shinobi/videos:/home/Shinobi/videos
           - /home/joss/data/shinobi/plugins:/home/Shinobi/plugins
           - /dev/shm/Shinobi/streams:/dev/shm/streams
        ports:
           - 9000:8080
        restart: unless-stopped

